### PR TITLE
sanfilip windows curses fix

### PR DESCRIPTION
**Pull request by sanfilip**

### CODE REVIEW

**Review by marquiswashere — APPROVED** [review]
LGTM 👍

**Comment by sanfilip** [comment]
@cwetherill-ps @lamroger the tests seem broken unrelated to my change.  Also there doesn't seem to be any deveoper readme here anymore on how to build and validate this open-source repo of ours.  Is there documentation elsewhere?

**Comment by cwetherill-ps** [comment]
```
../gradient/api_sdk/repositories/gradient_deployments.py:1: in <module>
    from gql import gql
E   ModuleNotFoundError: No module named 'gql'
```
@lamroger are we missing this in the tests' dependencies somewhere?

**Comment by sanfilip** [comment]
@lamroger I think I figured it out.  The dist build doesn't actually detect malformed dependencies, and I missed a comma.

**Pull request merged**
